apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: micro-pay
    app.kubernetes.io/name: micro-pay
  name: micro-pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: micro-pay
      app.kubernetes.io/name: micro-pay
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: micro-pay
        app.kubernetes.io/name: micro-pay
    spec:
      containers:
        - image: registry.devops.rivtower.com/web5/micro-pay:${MICRO_PAY_VERSION}
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: postgres
            - name: PORT
              value: '${MICRO_PAY_PORT}'
            - name: PLATFORM_MNEMONIC
              value: ${MICRO_PAY_PLATFORM_MNEMONIC}
            - name: PLATFORM_ADDRESS_COUNT
              value: '2'
            - name: CKB_NODE_URL
              value: https://testnet.ckb.dev/rpc
            - name: CKB_NETWORK
              value: ckb_testnet
          name: micro-pay
          ports:
            - containerPort: ${MICRO_PAY_PORT}
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 4000m
              memory: 4096Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext: {}
        - image: m.daocloud.io/docker.io/postgres:17-bookworm
          imagePullPolicy: IfNotPresent
          name: database
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_INITDB_ARGS
              value: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          resources:
            limits:
              cpu: 4000m
              memory: 4096Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database
  volumeClaimTemplates:
    - metadata:
        name: database
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: local-path
        resources:
          requests:
            storage: 50Gi
